chore: wip

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -44,4 +44,10 @@ jobs:
             export DB_USERNAME=${{ secrets.DB_USERNAME }}
             export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
             export SCHEMA_CONTEXT=${{ secrets.SCHEMA_CONTEXT }}
-            nohup java -jar /home/ec2-user/shopping-java.jar --spring.profiles.active=prod > app.log 2>&1 &
+            nohup java -jar /home/ec2-user/shopping-java.jar --spring.profiles.active=prod > app.log 2> app-error.log &
+            ps aux | grep shopping-java.jar
+            ls -l app.log app-error.log || echo "No se encontraron logs"
+            tail -n 50 app.log || echo "No hay contenido en app.log"
+            tail -n 50 app-error.log || echo "No hay contenido en app-error.log"
+
+
