feat: Add Import service file endpoint and action to deploy on ec2  (#9)
* feat: remove schema from DAO

* feat: add faker data

* feat: add mothers

* feat: add context case

* feat: add new test

* fix: comment dependency

* feat: add test integration and profile test and schema test

* feat: Add Liquibase implementation (#3)

* feat: add dependency liquibase

* feat: set price in numeric

* feat: add client to liquibase

* feat: add config to create schema first

* feat: add test to client package

* feat: add profile postgres

* feat: add var.env

* feat: add logger

* Create codeql.yml

* feat: codeql.yml

* feat: codeql.yml

* Create sonarcloud.yml

* feat: add test

* feat: sonarcloud.yml

* feat: sonarcloud.yml

* feat: sonarcloud

* feat: sonarcloud

* feat: sonarcloud

* feat: sonarcloud

* feat: pr template

* feat: modify PR template

* feat: add coverage to sonar (#5)

* feat: add coverage

* feat: add jacoco

* feat: add coverage (#6)

* feat: add coverage

* feat: add jacoco

* feat: add exclusions to sonar

* chore: add exclusion to sonar

* chore: add report generation step

* chore: add exclusion to sonar coverage

* feat: add cache implementation (#7)

* chore: add cache dependency

* feat: add cache implementation

* feat: add test to ClientCacheManagerTest

* fix: replace random by secure random

* fix: error compatibility with liquibase

* feat: add data layer

* feat: implement import service file creation use case

* feat: add import service file creation use case and related tests

* feat: add tests for ImportServiceFileRepositoryImpl and enhance ImportServiceFileMother

* chore: replace version by sha

* feat: implement import file handling and validation in import service

* feat: implement import file handling and validation in import service

* feat: enhance import service with content type handling and validation

* feat: add status tracking and error handling to ImportServiceFile

* chore: add tomcat server

* feat: add table to liquibase

* feat: update import service to include status and timestamps in response

* feat: update application configuration and add demo data for import service

* feat: implement auditing for ImportServiceFile with created and updated timestamps

* feat: add status field to ImportServiceFile with enumerated type

* feat: remove auditing fields from ImportServiceFile and related classes

* feat: add GetImportServiceFileUseCase and endpoint to retrieve import service files

* feat: remove unnecessary fields from ImportServiceFileResponse

* chore: add AWS deployment configuration and setup scripts for EC2

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -75,12 +75,20 @@ jobs:
             -DskipITs \
             -DskipTests=false
 
+      - name: Verify JaCoCo Report Generation
+        run: |
+          if [ -f target/site/jacoco/jacoco.xml ]; then
+              echo "JaCoCo report generated successfully."
+          else
+              echo "JaCoCo report not found. Exiting."
+              exit 1
+          fi
       - name: Analyze with SonarCloud
         # You can pin the exact commit or the version.
         # uses: SonarSource/sonarcloud-github-action@v2.2.0
-        uses: SonarSource/sonarcloud-github-action@v2.2.0
+        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
         env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         with:
           # Additional arguments for the SonarScanner CLI
           args:
@@ -89,11 +97,9 @@ jobs:
             -Dsonar.projectKey=${{ env.PROJECT_KEY }}
             -Dsonar.organization=${{ env.ORG_KEY }}
             -Dsonar.java.binaries=target/classes
-          # Comma-separated paths to directories containing main source files.
-          #-Dsonar.sources= # optional, default is project base directory
-          # Comma-separated paths to directories containing test source files.
-          #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
-          # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
-          #-Dsonar.verbose= # optional, default is false
-          # When you need the analysis to take place in a directory other than the one from which it was launched, default is .
+            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
+            -Dsonar.scanner.forceAnalysis=false
+            -Dsonar.exclusions=**/*DTO.java,**/*DAO.java
+            -Dsonar.test.exclusions=**/test/**,**/*Test.java
+            -Dsonar.coverage.exclusions=**/test/**,**/*Test.java
           projectBaseDir: .
